[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@google/genai", "busboy"]

[[redirects]]
  from = "/api/*"
  to = "https://aidesignengine.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
